services:
  front-end:
    build:
      context: ./front-end
      dockerfile: dockerfile
    image:
      task4:front-end
    ports:
      - "9000:9000"
    depends_on:
      - back-end

  back-end:
    build:
      context: ./back-end
      dockerfile: dockerfile
    image:
      task4:back-end
    ports:
      -  "5252:5252"